# Use the official PostgreSQL image
FROM postgres:latest

# Set environment variables for database configuration
ENV POSTGRES_DB=dakaDB
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=1234

# Expose PostgreSQL default port
EXPOSE 5432
